baseurl: /downtown-archaeologies
name: Downtown Archæologies
markdown: kramdown
collections:
  artifacts :
    output: true
defaults: 
  -
    scope: 
      path: ""
    values:
      layout: "default"
  -
    scope: 
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: artifacts
    values:
      layout: artifact
      map: true
