baseurl: /downtown-archaeologies
name: Downtown Archæologies
markdown: kramdown
include: ["_pages"]
collections:
  artifacts :
    output: true
  nodes:
    output: true
defaults: 
  -
    scope: 
      path: ""
    values:
      layout: "default"
  -
    scope: 
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: artifacts
    values:
      layout: artifact
  -
    scope:
      path: ""
      type: nodes
    values:
      layout: node
